# **Machine Leaning**
## *Lab Session 1*
### SET A 

In [1]:
from itertools import combinations
import numpy as np

### Functions

In [2]:
# Question 2
def get_range(list_of_nums:list):
    if len(list_of_nums) <= 3:
        return "Range Determination Not possible"
    list_of_nums.sort()
    return (list_of_nums[-1] - list_of_nums[0])
    
# Question 3
def mat_pow(A,m):
    return np.linalg.matrix_power(A,m)

#### **Q1.** Consider the given list as [2, 7, 4, 1, 3, 6]. Write a program to count pairs of elements with sum equal to 10.

In [3]:
list1 = [2,7,4,1,3,6]
# get all the combintaions
pairs = list(combinations(list1,2))
# filter the list to obtain the paris with sum 10
pairs_with_sum_10 = list(filter(lambda item: item[0]+item[1]==10, pairs))
pairs_with_sum_10

[(7, 3), (4, 6)]

#### **Q2.** Write a program that takes a list of real numbers as input and returns the range (difference between minimum and maximum) of the list. Check for list being less than 3 elements in which case return an error message (Ex: “Range determination not possible”). Given a list [5,3,8,1,0,4], the range is 8 (8-0).

In [4]:
list2 = list(map(int, input("Enter a list of nums: ").split()))
print(get_range(list2))

Enter a list of nums:  1 2 3 4 5 6 7 8


7


#### **Q3.** Write a program that accepts a square matrix A and a positive integer m as arguments and returns A<sup>m</sup>

In [6]:
A = np.array(eval(input("Enter a matrix : ")))
m = int(input("Enter the power : "))
print(np.matrix(np.linalg.matrix_power(A,10)))

Enter a matrix :  [[1,2,3],[4,5,6],[7,8,9]]
Enter the power :  5


[[132476037840 162775103256 193074168672]
 [300005963406 368621393481 437236823556]
 [467535888972 574467683706 681399478440]]


####  **Q4.** Write a program to count the highest occurring character & its occurrence count in an input string. Consider only alphabets. Ex: for “hippopotamus” as input string, the maximally occurring character is ‘p’ & occurrence count is 3.

In [7]:
string = input("Enter a string: ")
highest_occurance = ""
highest_occurance_count = 0
for character in set(string):
    c = string.count(character)
    if c > highest_occurance_count:
        highest_occurance = character
        highest_occurance_count = c
print(highest_occurance, " occured ", highest_occurance_count, " times." )        

Enter a string:  hippopotamus


p  occured  3  times.
